
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tan
 */
public class AdminRegister extends javax.swing.JFrame {

    /**
     * Creates new form AdminRegister
     */
    public AdminRegister() {
        initComponents();
        // i dont get ts
        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        SUB = new javax.swing.JTextField();
        IDNo = new javax.swing.JTextField();
        FirstN = new javax.swing.JTextField();
        UserN = new javax.swing.JTextField();
        LastN = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        PW = new javax.swing.JPasswordField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 180, 40));

        SUB.setBorder(null);
        SUB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBActionPerformed(evt);
            }
        });
        getContentPane().add(SUB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 190, -1));

        IDNo.setBorder(null);
        IDNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDNoActionPerformed(evt);
            }
        });
        getContentPane().add(IDNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 190, -1));

        FirstN.setBorder(null);
        getContentPane().add(FirstN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 190, -1));

        UserN.setBorder(null);
        UserN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNActionPerformed(evt);
            }
        });
        getContentPane().add(UserN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 264, 410, -1));

        LastN.setBorder(null);
        LastN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNActionPerformed(evt);
            }
        });
        getContentPane().add(LastN, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 190, -1));
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 70));

        PW.setBorder(null);
        PW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PWActionPerformed(evt);
            }
        });
        getContentPane().add(PW, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 200, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AdminRegister.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(FirstN.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "This Field Cannot be Empty", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if(LastN.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "This Field Cannot be Empty", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if(UserN.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "This Field Cannot be Empty", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if(SUB.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "This Field Cannot be Empty", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if(IDNo.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "This Field Cannot be Empty", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if(PW.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "This Field Cannot be Empty", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else {
        // what even is a db
        
        
        String fName = FirstN.getText();
        String lNamen = LastN.getText();
        String uName = UserN.getText();
        String subJ = SUB.getText();
        String idNum = IDNo.getText();
        String pWord = PW.getText();
        
        
        
        this.dispose();
        new AdminLogin().setVisible(true);}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LastNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNActionPerformed

    private void UserNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNActionPerformed

    private void SUBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SUBActionPerformed

    private void IDNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDNoActionPerformed

    private void PWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PWActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextField FirstN;
    private javax.swing.JTextField IDNo;
    private javax.swing.JTextField LastN;
    private javax.swing.JPasswordField PW;
    private javax.swing.JTextField SUB;
    private javax.swing.JTextField UserN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
