import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.ResultSet;  
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gianc
 */
public class chatteacher extends javax.swing.JFrame {
String username = "Teacher"; // or pass it from login later
    public chatteacher() {
        initComponents();
        this.dispose();
        setSize(1000, 550);
        this.setUndecorated(true);
        setLocationRelativeTo(null); // Centers the frame

        try {
    Connection();
} catch (SQLException ex) {
    Logger.getLogger(TeacherLogin.class.getName()).log(Level.SEVERE, null, ex);
}

this.setVisible(true);
loadMessages();
    }
        Connection con;
        Statement state;
        PreparedStatement pst;
        
        private static final String DbaseName = "tregister";
        private static final String DbaseDriver = "com.mysql.cj.jdbc.Driver";
        private static final String DbaseUrl = "jdbc:mysql://localhost:3306/"+DbaseName;
        private static final String DbaseUsername = "root";
        private static final String DbasePassword = "";
    
    public void Connection () throws SQLException{
        try {
            Class.forName(DbaseDriver);
            con = DriverManager.getConnection(DbaseUrl, DbaseUsername, DbasePassword);
            state = con.createStatement();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TeacherRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private void loadMessages() {
    try {
        textArea1.setText("");
        String sql = "SELECT sender_name, message FROM public_chat ORDER BY id ASC";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        while (rs.next()) {
            String sender = rs.getString("sender_name");
            String msg = rs.getString("message");
            textArea1.append((sender != null ? sender : "Anonymous") + ": " + msg + "\n");
        }
    } catch (Exception e) {
        System.out.println("Error loading messages: " + e.getMessage());
    }
}
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        textArea1 = new java.awt.TextArea();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollBar1 = new javax.swing.JScrollBar();
        textArea1 = new java.awt.TextArea();
        textArea1 = new java.awt.TextArea();
        textArea1 = new java.awt.TextArea();
        textArea1 = new java.awt.TextArea();
        textArea1 = new java.awt.TextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Public Chat");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 160, 50));

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 100, 40));

        jTextField1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 450, 40));

        textArea1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        textArea1.setText("awdawdawdawd");
        getContentPane().add(textArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 550, 330));

        scrollPane1.setForeground(new java.awt.Color(255, 0, 0));
        scrollPane1.add(jScrollBar1);

        textArea1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        textArea1.setText("awdawdawdawd");
        getContentPane().add(textArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 550, 330));

        textArea1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        textArea1.setText("awdawdawdawd");
        getContentPane().add(textArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 550, 330));

        textArea1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        textArea1.setText("awdawdawdawd");
        getContentPane().add(textArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 550, 330));

        textArea1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        textArea1.setText("awdawdawdawd");
        getContentPane().add(textArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 550, 330));

        textArea1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        textArea1.setText("awdawdawdawd");
        getContentPane().add(textArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 550, 330));

        getContentPane().add(scrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 550, 330));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/By registering, You agree to the Terms, Conditions and Policies of Borcelle & Privacy Policy (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String message = jTextField1.getText().trim();
    
  
    String[] badWords = {"bobo", "kamote", "tanga", "sex", "tarantado", "gago", "kupal", "tite", "pepe"};
    boolean containsBadWord = false;
    for (String word : badWords) {
        if (message.toLowerCase().contains(word)) {
            containsBadWord = true;
            break;
        }
    }

    if (containsBadWord) {
        JOptionPane.showMessageDialog(this, "Inappropriate language is not allowed!", "Warning", JOptionPane.WARNING_MESSAGE);
        jTextField1.setText("");
    } else if (!message.isEmpty()) {
        try {
            String sql = "INSERT INTO public_chat (sender_name, message) VALUES (?, ?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, username);
            pst.setString(2, message);
            pst.executeUpdate();

            jTextField1.setText("");
            loadMessages();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Failed to send message: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chatteacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chatteacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chatteacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chatteacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chatteacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField jTextField1;
    private java.awt.ScrollPane scrollPane1;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
