
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tan
 */
public class Dashboard extends javax.swing.JFrame {
        
    /**
     * Creates new form Dashboard
     */
        Color DefaultColor,ClickedColor;
    
    public Dashboard() {
        initComponents();
        this.dispose();
        setSize(1000, 550);
        this.setUndecorated(true);
        setLocationRelativeTo(null);
        this.setVisible(true);
        DefaultColor = new Color(242,242,242);
        ClickedColor = new Color(153,153,153);
        
        AnnouncePanel.setBackground(DefaultColor);
        ChatPanel.setBackground(DefaultColor);
        SchedulePanel.setBackground(DefaultColor);
        ProfilePanel.setBackground(DefaultColor);
        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        AnnouncePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ChatPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        SchedulePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ProfilePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MenuPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setName(""); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        AnnouncePanel.setBackground(new java.awt.Color(255, 255, 255));
        AnnouncePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AnnouncePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnnouncePanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AnnouncePanelMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel2.setText("Announcements");

        javax.swing.GroupLayout AnnouncePanelLayout = new javax.swing.GroupLayout(AnnouncePanel);
        AnnouncePanel.setLayout(AnnouncePanelLayout);
        AnnouncePanelLayout.setHorizontalGroup(
            AnnouncePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnnouncePanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        AnnouncePanelLayout.setVerticalGroup(
            AnnouncePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnnouncePanelLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        getContentPane().add(AnnouncePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 140, 30));

        ChatPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ChatPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChatPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ChatPanelMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel3.setText("Chat");

        javax.swing.GroupLayout ChatPanelLayout = new javax.swing.GroupLayout(ChatPanel);
        ChatPanel.setLayout(ChatPanelLayout);
        ChatPanelLayout.setHorizontalGroup(
            ChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChatPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        ChatPanelLayout.setVerticalGroup(
            ChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(ChatPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 140, 30));

        SchedulePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SchedulePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SchedulePanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SchedulePanelMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel4.setText("Schedule");

        javax.swing.GroupLayout SchedulePanelLayout = new javax.swing.GroupLayout(SchedulePanel);
        SchedulePanel.setLayout(SchedulePanelLayout);
        SchedulePanelLayout.setHorizontalGroup(
            SchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SchedulePanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        SchedulePanelLayout.setVerticalGroup(
            SchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SchedulePanelLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        getContentPane().add(SchedulePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 140, 30));

        ProfilePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ProfilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfilePanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProfilePanelMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel5.setText("Student Profile");

        javax.swing.GroupLayout ProfilePanelLayout = new javax.swing.GroupLayout(ProfilePanel);
        ProfilePanel.setLayout(ProfilePanelLayout);
        ProfilePanelLayout.setHorizontalGroup(
            ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilePanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        ProfilePanelLayout.setVerticalGroup(
            ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfilePanelLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        getContentPane().add(ProfilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 140, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dashboard.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        getContentPane().add(MenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 750, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnnouncePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnnouncePanelMousePressed
        // TODO add your handling code here:
        AnnouncePanel.setBackground(ClickedColor);
        ChatPanel.setBackground(DefaultColor);
        SchedulePanel.setBackground(DefaultColor);
        ProfilePanel.setBackground(DefaultColor);
    }//GEN-LAST:event_AnnouncePanelMousePressed

    private void ChatPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChatPanelMousePressed
        // TODO add your handling code here:
        ChatPanel.setBackground(ClickedColor);
        AnnouncePanel.setBackground(DefaultColor);
        SchedulePanel.setBackground(DefaultColor);
        ProfilePanel.setBackground(DefaultColor);
    }//GEN-LAST:event_ChatPanelMousePressed

    private void SchedulePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SchedulePanelMousePressed
        // TODO add your handling code here:
        SchedulePanel.setBackground(ClickedColor);
        AnnouncePanel.setBackground(DefaultColor);
        ChatPanel.setBackground(DefaultColor);
        ProfilePanel.setBackground(DefaultColor);
    }//GEN-LAST:event_SchedulePanelMousePressed

    private void AnnouncePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnnouncePanelMouseClicked
        // TODO add your handling code here:
        AdminAnnounce AdminAnnounce = new AdminAnnounce();
        MenuPanel.removeAll();
        MenuPanel.add(AdminAnnounce).setVisible(true);
    }//GEN-LAST:event_AnnouncePanelMouseClicked

    private void ChatPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChatPanelMouseClicked
        // TODO add your handling code here:
        AdminChat AdminChatt = new AdminChat();
        MenuPanel.removeAll();
        MenuPanel.add(AdminChatt).setVisible(true);
    }//GEN-LAST:event_ChatPanelMouseClicked

    private void SchedulePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SchedulePanelMouseClicked
        // TODO add your handling code here:
        AdminSched AdminSched = new AdminSched();
        MenuPanel.removeAll();
        MenuPanel.add(AdminSched).setVisible(true);
    }//GEN-LAST:event_SchedulePanelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ProfilePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilePanelMousePressed
        // TODO add your handling code here:
        ProfilePanel.setBackground(ClickedColor);
        AnnouncePanel.setBackground(DefaultColor);
        ChatPanel.setBackground(DefaultColor);
        SchedulePanel.setBackground(DefaultColor);
    }//GEN-LAST:event_ProfilePanelMousePressed

    private void ProfilePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilePanelMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_ProfilePanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
                
            }
        }); 
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AnnouncePanel;
    private javax.swing.JPanel ChatPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel ProfilePanel;
    private javax.swing.JPanel SchedulePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
