

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet; 

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gianc
 */
public class Schedule extends javax.swing.JFrame {

    /**
     * Creates new form Schedule
     */
    public Schedule() {
        initComponents();
        this.dispose();
        setSize(1000, 550);
        this.setUndecorated(true);
        setLocationRelativeTo(null); // Centers the frame
        this.setVisible(true);
        loadTableData();
        try {
            Connection();
        } catch (SQLException ex) {
            Logger.getLogger(TeacherRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     Connection con;
        Statement state;
        PreparedStatement pst;
    
    private static final String DbaseName = "tregister";
    private static final String DbaseDriver = "com.mysql.cj.jdbc.Driver";
    private static final String DbaseUrl = "jdbc:mysql://localhost:3306/"+DbaseName;
    private static final String DbaseUsername = "root";
    private static final String DbasePassword = "";
    
    public void Connection () throws SQLException{
        try {
            Class.forName(DbaseDriver);
            con = DriverManager.getConnection(DbaseUrl, DbaseUsername, DbasePassword);
            state = con.createStatement();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TeacherRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    public void loadTableData() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Clear existing rows first
    model.setRowCount(0);

    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tregister", "root", "");
        String sql = "SELECT DISTINCT strand, year, section FROM schedule";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            String strand = rs.getString("strand");
            String year = rs.getString("year");
            String section = rs.getString("section");

            // Add only these 3 columns to the table
            model.addRow(new Object[]{strand, year, section});
        }

        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
}
    
    public void showFullSchedule(String strand, String year, String section) {
    StringBuilder schedule = new StringBuilder();
    schedule.append("Schedule for ").append(strand).append(" ")
            .append(year).append(" Section ").append(section)
            .append(":\n--------------------------\n");

    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tregister", "root", "");
        String sql = "SELECT * FROM schedule WHERE strand = ? AND year = ? AND section = ? ORDER BY FIELD(day, 'Monday','Tuesday','Wednesday','Thursday','Friday'), time_from";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, strand);
        pst.setString(2, year);
        pst.setString(3, section);
        ResultSet rs = pst.executeQuery();

        String currentDay = "";
        while (rs.next()) {
            String day = rs.getString("day");
            if (!day.equals(currentDay)) {
                schedule.append("\n").append(day).append(":\n");
                currentDay = day;
            }
            String timeFrom = rs.getString("time_from");
            String timeTo = rs.getString("time_to");
            String subject = rs.getString("subject");
            String teacher = rs.getString("teacher_name");
            String room = rs.getString("room");

            schedule.append("  ").append(timeFrom).append(" - ").append(timeTo)
                    .append("  ").append(subject)
                    .append(" (").append(teacher).append(") @ Room: ").append(room)
                    .append("\n");
        }

        JOptionPane.showMessageDialog(null, schedule.toString());

        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "strand", "year", "section"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 930, -1));

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setText("Add Schedule");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, 360, 50));

        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, 100, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/By registering, You agree to the Terms, Conditions and Policies of Borcelle & Privacy Policy_1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String strand = JOptionPane.showInputDialog("Enter Strand:");
        String year = JOptionPane.showInputDialog("Enter Year:");
        String section = JOptionPane.showInputDialog("Enter Section:");
        String subject = JOptionPane.showInputDialog("Enter Subject:");
        String teacher = JOptionPane.showInputDialog("Enter Teacher Name:");
        String day = JOptionPane.showInputDialog("Enter Day (Monday-Friday):");
        String timeFrom = JOptionPane.showInputDialog("Enter Time From:");
        String timeTo = JOptionPane.showInputDialog("Enter Time To:");
        String room = JOptionPane.showInputDialog("Enter Room Number:");

    // Now insert this into your database
    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tregister", "root", "");
        String sql = "INSERT INTO schedule (strand, year, section, subject, teacher_name, day, time_from, time_to, room) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, strand);
        pst.setString(2, year);
        pst.setString(3, section);
        pst.setString(4, subject);
        pst.setString(5, teacher);
        pst.setString(6, day);
        pst.setString(7, timeFrom);
        pst.setString(8, timeTo);
        pst.setString(9, room);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(null, "Schedule added successfully!");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         int row = jTable1.getSelectedRow();
    String strand = jTable1.getValueAt(row, 0).toString();
    String year = jTable1.getValueAt(row, 1).toString();
    String section = jTable1.getValueAt(row, 2).toString();

    showFullSchedule(strand, year, section);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Teacher().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Schedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
