
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gianc
 */
public class StudentRegister extends javax.swing.JFrame {

    /**
     * Creates new form StudentRegister
     */
    public StudentRegister() {
        initComponents();
        this.dispose();
        setSize(1000, 550);
        this.setUndecorated(true);
        setLocationRelativeTo(null); // Centers the frame
        this.setVisible(true);
        try {
            Connection();
        } catch (SQLException ex) {
            Logger.getLogger(TeacherRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        Connection con;
        Statement state;
        PreparedStatement pst;
    
    private static final String DbaseName = "tregister";
    private static final String DbaseDriver = "com.mysql.cj.jdbc.Driver";
    private static final String DbaseUrl = "jdbc:mysql://localhost:3306/"+DbaseName;
    private static final String DbaseUsername = "root";
    private static final String DbasePassword = "";
    
    public void Connection () throws SQLException{
        try {
            Class.forName(DbaseDriver);
            con = DriverManager.getConnection(DbaseUrl, DbaseUsername, DbasePassword);
            state = con.createStatement();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TeacherRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NAME = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        SECTION = new javax.swing.JTextField();
        LAST = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NAME.setBackground(new java.awt.Color(255, 255, 255));
        NAME.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        NAME.setForeground(new java.awt.Color(0, 0, 0));
        NAME.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NAME.setBorder(null);
        NAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMEActionPerformed(evt);
            }
        });
        getContentPane().add(NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, 30));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 260, 30));

        SECTION.setBackground(new java.awt.Color(255, 255, 255));
        SECTION.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        SECTION.setForeground(new java.awt.Color(0, 0, 0));
        SECTION.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SECTION.setBorder(null);
        SECTION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SECTIONActionPerformed(evt);
            }
        });
        getContentPane().add(SECTION, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 130, 30));

        LAST.setBackground(new java.awt.Color(255, 255, 255));
        LAST.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        LAST.setForeground(new java.awt.Color(0, 0, 0));
        LAST.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LAST.setBorder(null);
        LAST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LASTActionPerformed(evt);
            }
        });
        getContentPane().add(LAST, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 160, 30));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField1.setBorder(null);
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 250, 30));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(null);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 150, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Register");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 170, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/By registering, You agree to the Terms, Conditions and Policies of Borcelle & Privacy Policy (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMEActionPerformed

    private void LASTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LASTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LASTActionPerformed

    private void SECTIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SECTIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SECTIONActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if ("".equals(jTextField1.getText())){
            JOptionPane.showMessageDialog(null, "User Can't Be Blank!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if ("".equals(jPasswordField1.getText())){
            JOptionPane.showMessageDialog(null, "Field Can't Be Blank!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if ("".equals(jTextField2.getText())){
            JOptionPane.showMessageDialog(null, "ID Number Can't Be Blank!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if ("".equals(NAME.getText())){
            JOptionPane.showMessageDialog(null, "First Name Can't Be Blank!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if ("".equals(LAST.getText())){
            JOptionPane.showMessageDialog(null, "Last Name Can't Be Blank!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if ("".equals(SECTION.getText())){
            JOptionPane.showMessageDialog(null, "Subject Can't Be Blank!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else {
           String Username = jTextField1.getText();
           String Password = new String(jPasswordField1.getPassword());
           String IDNumber = jTextField2.getText();
           String FName = NAME.getText();
           String LName = LAST.getText();
           String Section = SECTION.getText();
           
           String queryRegister = "INSERT INTO saccounts(SUSERNAME, SPASSWORD, SIDNUM, SFIRSTN, SLASTN, SECTION) VALUES (?, ?, ?, ?, ?, ?)";
            try {
                 pst = con.prepareStatement(queryRegister);
                 pst.setString(1, Username);  // Set Username to first placeholder
                 pst.setString(2, Password);  // Set Password to second placeholder
                 pst.setString(3, IDNumber); 
                 pst.setString(4, FName);
                 pst.setString(5, LName);
                 pst.setString(6, Section);
                 // Execute the update
                 pst.executeUpdate();

            } catch (SQLException ex) {
                Logger.getLogger(TeacherRegister.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "ACCOUNT CREATED", "REGISTRATION DONE!", JOptionPane.INFORMATION_MESSAGE);
            jTextField1.setText("");
            jPasswordField1.setText("");
            jTextField2.setText("");
            NAME.setText("");
            LAST.setText("");
            SECTION.setText("");
            new StudentRegister().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LAST;
    private javax.swing.JTextField NAME;
    private javax.swing.JTextField SECTION;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
